<?xml version="1.0"?>
<robot name='myfirstrobot' xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Xacro Porperties -->

<xacro:property name = 'pi' value = '3.1415926535897931'/>
<xacro:property name = 'length' value = '0.05'/>
<xacro:property name = 'radius' value = '0.1'/>



<!-- Inertial Xacro -->
<xacro:macro name='default_inertial' params = 'mass'>
  <inertial>
    <origin xyz = '0 0 0.1' rpy='0 0 0'/>
    <mass value = "${mass}"/>
    <inertia ixx ='1.0' ixy = '0.0' ixz = '0.0' iyy = '1.0' iyz = '0.0' izz = '1.0'/>
  </inertial>
</xacro:macro>

<!--Wheels Xacro -->
<xacro:macro name = 'wheel' params = 'prefix reflect'>
  <link name = '${prefix}_wheel'>
    <visual>
      <origin xyz = '0.1 ${reflect * 0.125} 0.1' rpy = '0 ${pi/2} ${pi/2}'/>
      <geometry>
        <cylinder radius = "${radius}" length = '${length}'/>
      </geometry>
    </visual>

    <collision>
      <origin xyz = '0.1 ${reflect * 0.13} 0.1' rpy = '0 ${pi/2} ${pi/2}'/>
      <geometry>
        <cylinder radius = "${radius}" length = '${length}'/>
      </geometry>
    </collision>

    <xacro:default_inertial mass = '1' />
  </link>

  <joint name = "${prefix}_wheel_hinge" type = 'continuous'>
    <axis xyz = '0 1 0'/>
    <origin xyz = '0 0 0' rpy = '0 0 0'/>
    <parent link = 'base_link'/>
    <child link = '${prefix}_wheel'/>
  </joint>
</xacro:macro>

<!-- Start of Definition -->
  <link name = 'base_link'>
    <visual>
      <origin xyz = '0 0 0.1' rpy='0 0 0'/>
      <geometry>
        <box size = '0.4 0.2 0.1'/>
      </geometry>
    </visual>

    <collision>
      <origin xyz = '0 0 0.1' rpy='0 0 0'/>
      <geometry>
        <box size = '0.4 0.2 0.1'/>
      </geometry>
    </collision>

    <xacro:default_inertial mass = '10'/>
  </link>

  <xacro:wheel prefix = 'right' reflect = '-1'/>
  <xacro:wheel prefix = 'left' reflect = '1'/>

  <link name = 'caster_wheel'>
    <visual>
      <origin xyz = '-0.15 0 0.05' rpy = '0 0 0'/>
      <geometry>
        <sphere radius = '0.05'/>
      </geometry>
    </visual>

    <collision>
      <origin xyz = '-0.15 0 0.05' rpy = '0 0 0'/>
      <geometry>
        <sphere radius = '0.05'/>
      </geometry>
      <gazebo>
       <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </gazebo>
    </collision>

    <xacro:default_inertial mass = '0.5'/>
  </link>

 <joint name = 'caster_wheel_joint' type = 'fixed'>
  <origin xyz='0 0 0' rpy ='0 0 0'/>
  <parent link = 'base_link'/>
  <child link = 'caster_wheel'/>
 </joint>

 <gazebo>
   <plugin name ='differential_drive_controller' filename = 'libgazebo_ros_diff_drive.so'>
     <legacyMode>true</legacyMode>
     <rosDebugLevel>Debug</rosDebugLevel>
     <publishWheelTF>false</publishWheelTF>
     <robotNamespace>/</robotNamespace>
     <publishTf>1</publishTf>
     <publishWheelJointState>false</publishWheelJointState>
     <alwaysOn>true</alwaysOn>
     <updateRate>100.0</updateRate>
     <leftJoint>left_wheel_hinge</leftJoint>
     <rightJoint>right_wheel_hinge</rightJoint>
     <wheelSeparation>0.4</wheelSeparation>
     <wheelDiameter>${2*radius}</wheelDiameter>
     <broadcastTF>1</broadcastTF>
     <wheelTorque>30</wheelTorque>
     <wheelAcceleration>1.8</wheelAcceleration>
     <commandTopic>cmd_vel</commandTopic>
     <odometryFrame>odom</odometryFrame>
     <odometryTopic>odom</odometryTopic>
     <robotBaseFrame>base_link</robotBaseFrame>
   </plugin>
 </gazebo>

</robot>
