<?xml version="1.0" ?>
<robot xmlns:xacro ="http://www.ros.org/wiki/xacro" name = 'workbot'>

  <xacro:property name = 'base_width' value='0.4'/>
  <xacro:property name = 'base_length' value = '0.4'/>
  <xacro:property name = 'base_height' value = '0.025'/>

  <xacro:property name= 'wheel_radius' value = '0.085'/>
  <xacro:property name ='wheel_length' value = '0.05'/>

  <xacro:property name = 'caster_wheel_radius' value='0.04'/>
  <xacro:property name='caster_wheel_joint_offset' value='-0.15'/>

  <xacro:property name='wheel_joint_offset' value = '0.05'/>
  <xacro:property name="wheel_separation" value="0.325"/>
  <xacro:property name='base_wheel_gap' value='0.0175'/>

  <xacro:property name='laser_size_x' value='0.1'/>
  <xacro:property name='laser_size_y' value='0.1'/>
  <xacro:property name='laser_size_z' value='0.06'/>
  <xacro:property name='laser_origin_x' value='0.15'/>
  <xacro:property name='laser_origin_y' value='0'/>
  <xacro:property name='laser_origin_z' value='0.0175'/>



  <xacro:macro name = 'box_inertia' params = 'mass x y z'>
    <inertial>
      <mass value = '${mass}'/>
      <inertia ixx = '${mass / 12 * (z*z + y*y)}' ixy = '0.0' ixz = '0.0'
               iyy = '${mass / 12 * (x*x + y*y)}' iyz = '0.0'
               izz = '${mass / 12 * (x*x + z*z)}' />
    </inertial>
  </xacro:macro>

  <xacro:macro name='cylinder_inertia' params ='mass r l'>
    <inertial>
      <mass value = '${mass}'/>
      <inertia ixx='${mass*(3*r*r + l*l) / 12}' ixy='0.0' ixz='0.0'
               iyy='${mass*(3*r*r + l*l) / 12}' iyz='0.0'
               izz='${mass*r*r / 2}' />
    </inertial>
  </xacro:macro>

  <xacro:macro name='sphere_inertia' params='mass r'>
    <inertial>
      <mass value = '${mass}'/>
      <inertia ixx='${mass*2*(r*r)/5}' ixy='0.0' ixz='0.0'
               iyy='${mass*2*(r*r)/5}' iyz='0.0'
               izz='${mass*2*(r*r)/5}' />
    </inertial>
  </xacro:macro>


  <xacro:macro name='wheel' params='prefix reflect'>
    <link name='${prefix}_wheel'>
      <visual>
        <origin xyz='0 0 0' rpy = '${pi/2} 0 0'/>
        <geometry>
          <cylinder radius='${wheel_radius}' length='${wheel_length}'/>
        </geometry>
      </visual>

      <collision>
        <origin xyz='0 0 0' rpy = '${pi/2} 0 0'/>
        <geometry>
          <cylinder radius='${wheel_radius}' length='${wheel_length}'/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia mass='0.5' r='${wheel_radius}' l='${wheel_length}'/>
    </link>

    <joint name='${prefix}_wheel_joint' type='continuous'>
      <origin xyz='${wheel_joint_offset} ${((base_width/2)+base_wheel_gap)*reflect} -0.005' rpy='0 0 0'/>
      <axis xyz='0 1 0' rpy='0 0 0'/>
      <parent link='base_link'/>
      <child link='${prefix}_wheel'/>
    </joint>
  </xacro:macro>

  <link name = 'base_footprint'>
    <!--xacro:box_inertia mass='10' x='0.001' y='0.001' z='0.001'/--> 
    <visual>
      <origin xyz='0 0 0' rpy='0 0 0'/>
      <geometry>
        <box size = '0.001 0.001 0.001'/>
      </geometry>
    </visual>
  </link>


  <link name = 'base_link'>
    <xacro:box_inertia mass='1' x='${base_length}' y='${base_width}' z='${base_height}'/>

    <visual>
      <geometry>
        <box size = '${base_length} ${base_width} ${base_height}'/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size = '${base_length} ${base_width} ${base_height}'/>
      </geometry>
    </collision>
  </link>

  <joint name='base_link_joint' type ='fixed'>
    <origin xyz = '0 0 ${wheel_radius + 0.005}' rpy='0 0 0'/>
    <parent link='base_footprint'/>
    <child link='base_link'/>
  </joint>

  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <link name='caster_wheel'>
    <visual>
      <origin xyz='0 0 0' rpy='0 0 0'/>
      <geometry>
        <sphere radius='${caster_wheel_radius}'/>
      </geometry>
    </visual>

    <collision>
      <origin xyz='0 0 0' rpy='0 0 0'/>
      <geometry>
        <sphere radius='${caster_wheel_radius}'/>
      </geometry>
    </collision>

    <xacro:sphere_inertia mass='0.8' r='${caster_wheel_radius}'/>
  </link>

  <joint name='caster_wheel_joint' type='continuous'>
    <origin xyz='${caster_wheel_joint_offset} 0 -${caster_wheel_radius + 0.005}' rpy='0 0 0'/>
    <axis xyz= '0 1 0' rpy='0 0 0'/>
    <parent link='base_link'/>
    <child link='caster_wheel'/>
  </joint>

  <link name='sensor_laser'>
    <visual>
      <geometry>
        <box size='${laser_size_x} ${laser_size_y} ${laser_size_z}'/>
      </geometry>
    </visual>

    <!--<collision>
      <geometry>
        <box size='${laser_size_x} ${laser_size_y} ${laser_size_z}'/>
      </geometry>
    </collision> -->

    <xacro:box_inertia mass='0.2' x='${laser_size_x}' y='${laser_size_y}' z='${laser_size_z}'/>
  </link>

  <joint name='sensor_laser_joint' type='fixed'>
    <origin xyz='${laser_origin_x} ${laser_origin_y} ${laser_origin_z}' rpy='0 0 0'/>
    <parent link='base_link'/>
    <child link='sensor_laser'/>
  </joint>


  <xacro:include filename='$(find mybot_description)/urdf/robot_gazebo_plugins.xacro'/>
</robot>
